### ISSUE TITLE
Plugin causes ~2.4Mbps outside AGDSN network

### ISSUE THREAD

**Issue by toothstone** [agdsn/trafficplugin#2]
While being outside the AGDSN IP ranges, the plugin constantly queries the AGDSN servers (atlantis, zaphod, zeus, homer) causing lots of traffic.

**Comment by gwTumm** [comment]
¯\_(ツ)_/¯

**Comment by timklge** [comment]
¯\_(ツ)_/¯

**Comment by toothstone** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by toothstone** [comment]
Worst part about it is the increased power consumption of wifi hardware due to the constant activity.

**Comment by timklge** [comment]
k

**Comment by timklge** [comment]
There was an issue with the error event which caused the update mechnism to go in an infinite loop. Should be fixed now. Not in Chrome Web Store yet.

**Comment by timklge** [comment]
The new version (2.0.3) is now available via the chrome web store and chrome should automatically update the plugin. Please reopen this issue if the propblem persits.
